name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: debug file structure
      run: ls -R
        
    - name: Restore dependencies
      run: dotnet restore 
      
    - name: create artifact
      run: dotnet publish -c Release -r win-x64 /p:PublishSingleFile=true D:\a\devops_webscraper\devops_webscraper\webscraper_devops\webscraper
        
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Tim_Grevendonk_webscraper
        path: devops_webscraper/webscraper_devops/webscraper/bin/Debug/
