name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: debug file structure
      run: ls -R
        
    - name: Restore dependencies
      run: dotnet restore D:\a\devops_webscraper\devops_webscraper\webscraper_devops\webscraper
      
    - name: Build
      run: dotnet build --no-restore D:\a\devops_webscraper\devops_webscraper\webscraper_devops\webscraper
      
    - name: Test
      run: dotnet test --no-build --verbosity normal D:\a\devops_webscraper\devops_webscraper\webscraper_devops\webscraper
      
    - name: artifact
      run: |
        mkdir theExe
        cd D:\a\devops_webscraper\devops_webscraper\webscraper_devops\webscraper\obj\Debug
        cp webscraper.exe D:\a\devops_webscraper\
        
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Tim_Grevendonk_webscraper
        path: D:\a\devops_webscraper\devops_webscraper\theExe
