name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: debug file structure
      run: ls -R
        
    - name: Restore dependencies
      run: dotnet restore devops_webscraper/webscraper_devops/webscraper/
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Publish
      run: dotnet publish -r win-x64 -c Release --self-contained
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Tim_Grevendonk_webscraper
        path: publish
